In [1]:
import os

In [2]:
opfilelocneo = r"/home/rohit/PyWDUbuntu/thesis/Imgs2Detect_op4neo1"
print(f"exists = {os.path.exists(opfilelocneo)}")
print(f"dir = {os.path.isdir(opfilelocneo)}")
print(f"file = {os.path.isfile(opfilelocneo)}")

exists = False
dir = False
file = False


In [3]:
try:
    if not os.path.isdir(opfilelocneo):
        os.makedirs(opfilelocneo) # already exists
except:
    print(f"FATAL ERROR creating output directory")

In [4]:
print(f"exists = {os.path.exists(opfilelocneo)}")
print(f"dir = {os.path.isdir(opfilelocneo)}")
print(f"file = {os.path.isfile(opfilelocneo)}")

exists = True
dir = True
file = False


In [31]:
def ftotalout():
    print(f"Ran ftotalout")
class Outer():
    def of1(self):
        print(f"Ran of1")
    def run_if1(self):
        self.Inner.if1(self)
    class Inner():
        def if1(self):
            print(f"Ran if1")
            print(f"Calling ftotalout")
            ftotalout()
            print(f"Calling if2")
            self.Inner.if2(self)
        def if2(self):
            print(f"Ran if2")

In [32]:
o = Outer()

In [33]:
o.run_if1()

Ran if1
Calling ftotalout
Ran ftotalout
Calling if2
Ran if2


In [34]:
o.of1()

Ran of1


In [35]:
o.if1()

AttributeError: 'Outer' object has no attribute 'if1'

In [36]:
o.Inner.if1()

TypeError: if1() missing 1 required positional argument: 'self'

In [1]:
# multiprocessing using task and queue
# https://pymotw.com/2/multiprocessing/communication.html

In [1]:
import multiprocessing, os

In [2]:
image_path = r"/home/rohit/PyWDUbuntu/thesis/Imgs2Detect"
image_files_arr = [os.path.join(image_path, f) for f in os.listdir(image_path) if os.path.isfile(os.path.join(image_path, f))]

In [3]:
len(image_files_arr)

12

In [4]:
nfts = 2
num_jobs = int(len(image_files_arr) / nfts + ( (len(image_files_arr) % nfts)!=0 ) * 1)
print(f"{num_jobs}")

6


In [5]:
image_files_arr

['/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371903.jpg',
 '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371902 (copy).jpg',
 '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/36979 (copy).jpg',
 '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371897.jpg',
 '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/36979.jpg',
 '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/1317156 (copy).jpg',
 '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/148284.jpg',
 '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/148284 (copy).jpg',
 '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371897 (copy).jpg',
 '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/1317156.jpg',
 '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371903 (copy).jpg',
 '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371902.jpg']

In [6]:
if num_jobs > 1:
    for i in range(num_jobs - 1):
        print(f"job {i+1} =\n{image_files_arr[i*nfts : (i+1)*nfts]}")
print(f"job {num_jobs} =\n{image_files_arr[(num_jobs-1)*nfts : ]}")

job 1 =
['/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371903.jpg', '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371902 (copy).jpg']
job 2 =
['/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/36979 (copy).jpg', '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371897.jpg']
job 3 =
['/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/36979.jpg', '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/1317156 (copy).jpg']
job 4 =
['/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/148284.jpg', '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/148284 (copy).jpg']
job 5 =
['/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371897 (copy).jpg', '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/1317156.jpg']
job 6 =
['/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371903 (copy).jpg', '/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371902.jpg']


In [7]:
multiprocessing.cpu_count() - 1

11

In [8]:
class Consumer(multiprocessing.Process):
    def __init__(self, task_queue, result_queue):
        multiprocessing.Process.__init__(self)
        self.task_queue = task_queue
        self.result_queue = result_queue

    def run(self):
        proc_name = self.name
        while True:
            next_task = self.task_queue.get()
            if next_task is None:
                # Poison pill means shutdown
                print(f"Exiting process {proc_name}")
                self.task_queue.task_done()
                break
            print(f"Process {proc_name} picked job = {next_task.job_num}")
            answer = next_task()
            self.task_queue.task_done()
            self.result_queue.put(answer)
        return

In [9]:
class Task(object):
    def __init__(self, _job_num, _data_arr):
        self.job_num = _job_num
        self.data_arr = _data_arr
    def __call__(self):
        ans = []
        for each_entry in self.data_arr:
            ans.append("j" + str(self.job_num) + "_" + each_entry)
        return ans
    def __str__(self):
        return '%s * %s' % (self.a, self.b)

In [10]:
if __name__ == '__main__':
    
    image_path = r"/home/rohit/PyWDUbuntu/thesis/Imgs2Detect"
    image_files_arr = [os.path.join(image_path, f) for f in os.listdir(image_path) if os.path.isfile(os.path.join(image_path, f))]
    nfts = 2 # num of files per task

    # Establish communication queues
    tasks = multiprocessing.JoinableQueue()
    results = multiprocessing.Queue()
    
    # Start consumers
    num_consumers = multiprocessing.cpu_count() - 1
    print(f"Creating {num_consumers} consumers")
    consumers = [ Consumer(tasks, results) for i in range(num_consumers) ]
    for w in consumers:
        w.start()
    
    # Enqueue jobs
    num_jobs = int(len(image_files_arr) / nfts + ( (len(image_files_arr) % nfts)!=0 ) * 1)
    if num_jobs > 1:
        for i in range(num_jobs - 1):
            #print(f"job {i+1} =\n{image_files_arr[i*nfts : (i+1)*nfts]}")
            tasks.put(Task(i+1, image_files_arr[i*nfts : (i+1)*nfts]))
    #print(f"job {num_jobs} =\n{image_files_arr[(num_jobs-1)*nfts : ]}")
    tasks.put(Task(num_jobs, image_files_arr[(num_jobs-1)*nfts : ]))
    
    # Add a poison pill for each consumer
    for i in range(num_consumers):
        tasks.put(None)

    # Wait for all of the tasks to finish
    tasks.join()
    print(f"\n\nAll consumers rejoined\n\n")
    
    # Start printing results
    for i in range(num_jobs):
        result = results.get()
        print(f"Job {i+1} result=\n{result}")

Creating 11 consumers
Process Consumer-1 picked job = 1
Process Consumer-2 picked job = 2
Process Consumer-3 picked job = 3
Process Consumer-5 picked job = 5
Exiting process Consumer-11
Process Consumer-4 picked job = 4
Process Consumer-6 picked job = 6
Exiting process Consumer-10
Exiting process Consumer-1
Exiting process Consumer-6
Exiting process Consumer-5
Exiting process Consumer-3
Exiting process Consumer-4
Exiting process Consumer-2
Exiting process Consumer-7
Exiting process Consumer-8
Exiting process Consumer-9


All consumers rejoined


Job 1 result=
['j3_/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/36979.jpg', 'j3_/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/1317156 (copy).jpg']
Job 2 result=
['j6_/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371903 (copy).jpg', 'j6_/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371902.jpg']
Job 3 result=
['j5_/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/371897 (copy).jpg', 'j5_/home/rohit/PyWDUbuntu/thesis/Imgs2Detect/1317156.jpg']
Job 4 result=
['j1_/home/ro

In [11]:
import os

In [12]:
with open("dAta.json", "w") as f:
    print(f"{f}")

<_io.TextIOWrapper name='dAta.json' mode='w' encoding='UTF-8'>


In [13]:
f.name

'dAta.json'

In [14]:
os.path.realpath(f.name)

'/home/rohit/PyWDUbuntu/thesis/dAta.json'

In [1]:
import os

In [2]:
image_path = r"/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/"

In [ ]:
from os import listdir
from os.path import isfile, join

In [7]:
onlyfiles = [os.path.join(image_path, f) for f in os.listdir(image_path) if os.path.isfile(os.path.join(image_path, f))]

In [8]:
onlyfiles

['/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/301246.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/371903.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/3765589.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/2192573.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/4576671.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/5521996.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/960092.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/6054169.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/5791070.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/2868798.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/793558.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/5558592.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/5217116.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/5914327.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/5377361.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/5287405.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2Detect/490870.jpg',
 '/home/rohit/PyWDUbuntu/DA4_1/Imgs2

In [37]:
print(os.path.basename(onlyfiles[0]))

301246.jpg


In [38]:
print(os.path.basename(image_path))

In [40]:
ar1 = []
ar1.append({"img_name": os.path.basename(onlyfiles[0]) , "detections": [] } )

In [41]:
ar1

[{'img_name': '301246.jpg', 'detections': []}]

In [44]:
ar1[0]

{'img_name': '301246.jpg', 'detections': []}

In [45]:
ar1[0]["detections"]

[]

In [46]:
ar1[0]["detections"].append(["dog",0.456])

In [47]:
ar1

[{'img_name': '301246.jpg', 'detections': [['dog', 0.456]]}]

In [17]:
d = {"a": "abcds", "b": {"b1": 1, "b2": 2, "b3": "rohit", "b4": "bewoor"}}

In [21]:
d["b"]["b3"]

'rohit'

In [22]:
d = [{"img_name": "img1.jpg", "detections": [["label1", "label1_score"], ["label2", "label2_score"] ] } , {"img_name": "img2.jpg", "detections": [["label3", "label3_score"], ["label4", "label4_score"] ] } ]

In [26]:
for eachd in d[0:1]:
    print(f"{d}")

[{'img_name': 'img1.jpg', 'detections': [['label1', 'label1_score'], ['label2', 'label2_score']]}, {'img_name': 'img2.jpg', 'detections': [['label3', 'label3_score'], ['label4', 'label4_score']]}]


In [36]:
for idx, eachd in enumerate(d):
    print(f'{idx + 1} : image = {eachd["img_name"]}')
    for eachdet in eachd["detections"]:
        print(f'class = {eachdet[0]}\tscore = {eachdet[1]}')
    print(f"\n\n")

1 : image = img1.jpg
class = label1	score = label1_score
class = label2	score = label2_score



2 : image = img2.jpg
class = label3	score = label3_score
class = label4	score = label4_score





In [48]:
round(1.445324, 3)

1.445

In [1]:
import numpy as np

In [4]:
ar1 = np.array(np.ones((2,3)))

In [5]:
ar1.shape

(2, 3)

In [6]:
ar2 = np.expand_dims(ar1, 0)

In [7]:
ar2.shape

(1, 2, 3)

In [8]:
id(ar2)

140376510218688

In [10]:
ar3 = ar2.copy()

In [11]:
id(ar3)

140376510249200

In [1]:
import numpy as np
from keras.layers import Conv2D, Input, BatchNormalization, LeakyReLU, ZeroPadding2D, UpSampling2D
from keras.layers.merge import add, concatenate
from keras.models import Model
from keras import backend as K

Using TensorFlow backend.


In [5]:
l1 = [[1., 2, 3], [4, 5, 6]]

In [6]:
#ar1 = np.array(np.ones((1, 2, 3, 1)))
#ar1 = np.array(np.ones((2, 3)))
ar1 = np.array(l1)

In [7]:
ar1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
ar1.shape

(2, 3)

In [9]:
ar1 = np.expand_dims(ar1, 0)

In [10]:
ar1.shape

(1, 2, 3)

In [11]:
ar1 = np.expand_dims(ar1, 3)

In [12]:
ar1.shape

(1, 2, 3, 1)

In [13]:
ar1

array([[[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]]])

In [14]:
type(ar1)

numpy.ndarray

In [15]:
ar2 = K.variable(value=ar1)

In [16]:
type(ar2)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [17]:
ar2

<tf.Variable 'Variable:0' shape=(1, 2, 3, 1) dtype=float32, numpy=
array([[[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]]], dtype=float32)>

In [18]:
ar2.shape

TensorShape([1, 2, 3, 1])

In [19]:
ar2 = ZeroPadding2D(((1,0),(1,0)))(ar2)

In [20]:
ar2

<tf.Tensor 'zero_padding2d_1/Pad:0' shape=(1, 3, 4, 1) dtype=float32>

In [21]:
ar3 = K.eval(ar2)

In [22]:
type(ar3)

numpy.ndarray

In [23]:
ar3

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [1.],
         [2.],
         [3.]],

        [[0.],
         [4.],
         [5.],
         [6.]]]], dtype=float32)

In [2]:
import json

neoarr = [{"img": "img1.jpg", "det": [["label1", "label1_score"], ["label2", "label2_score"] ] } , {"img": "img2.jpg", "det": [["label3", "label3_score"], ["label4", "label4_score"] ] } ]
print(f"type(neoarr) = {type(neoarr)}\nneoarr =\n{neoarr}")
with open("data.json", "w") as some_file:
    json.dump(neoarr, some_file)
del(neoarr)

with open("data.json", "r") as saved_file:
    neoarr = json.load(saved_file)
print(f"type(neoarr) = {type(neoarr)}\nneoarr =\n{neoarr}")

type(neoarr) = <class 'list'>
neoarr =
[{'img': 'img1.jpg', 'det': [['label1', 'label1_score'], ['label2', 'label2_score']]}, {'img': 'img2.jpg', 'det': [['label3', 'label3_score'], ['label4', 'label4_score']]}]
type(neoarr) = <class 'list'>
neoarr =
[{'img': 'img1.jpg', 'det': [['label1', 'label1_score'], ['label2', 'label2_score']]}, {'img': 'img2.jpg', 'det': [['label3', 'label3_score'], ['label4', 'label4_score']]}]


In [2]:
#from py2neo.data import Node, Relationship
from py2neo import Graph

In [3]:
graph = Graph(uri="bolt://localhost:7687",auth=("neo4j","abc"))

In [4]:
type(graph)

py2neo.database.Graph

In [5]:
graph

<Graph database=<Database uri='bolt://localhost:7687' secure=False user_agent='py2neo/4.3.0 neobolt/1.7.17 Python/3.7.7-final-0 (linux)'> name='data'>

In [6]:
tx = graph.begin()

In [7]:
tx.finished()

False

In [8]:
imgFile = "img1.jpg"
objDetected = "person"
detScore1 = 98.00
detScore2 = 50.00

In [9]:
stmt1 = r'MERGE (:Image {name: $_in_img_name})'
stmt2 = r'MERGE (:Object {name: $_in_obj_det})'
stmt3=r'MATCH (i1:Image{name: $_in_img_name}) MATCH (o1:Object{name: $_in_obj_det}) CREATE (i1)-[:HAS{score: $_in_det_score}]->(o1)'
stmt4=r'MATCH (i1:Image{name: $_in_img_name}) MATCH (o1:Object{name: $_in_obj_det}) CREATE (i1)-[:HAS{score: $_in_det_score}]->(o1)'

In [10]:
print(f"stmt1={stmt1}\nstmt2={stmt2}\nstmt3={stmt3}\nstmt4={stmt4}")

stmt1=MERGE (:Image {name: $_in_img_name})
stmt2=MERGE (:Object {name: $_in_obj_det})
stmt3=MATCH (i1:Image{name: $_in_img_name}) MATCH (o1:Object{name: $_in_obj_det}) CREATE (i1)-[:HAS{score: $_in_det_score}]->(o1)
stmt4=MATCH (i1:Image{name: $_in_img_name}) MATCH (o1:Object{name: $_in_obj_det}) CREATE (i1)-[:HAS{score: $_in_det_score}]->(o1)


In [11]:
#tx.run(stmt1, parameters={"_in_img_name": in_imgFile})
tx.run(stmt1, parameters={"_in_img_name": imgFile})
tx.run(stmt2, parameters={"_in_obj_det": objDetected})
tx.run(stmt3, parameters={"_in_img_name": imgFile, "_in_obj_det": objDetected, "_in_det_score": detScore1})
tx.run(stmt4, parameters={"_in_img_name": imgFile, "_in_obj_det": objDetected, "_in_det_score": detScore2})

In [12]:
tx.commit()

In [13]:
tx.finished()

True

In [8]:
stmt1 = 'MERGE (:Image {name: "' + in_imgFile + '"})'
stmt2 = 'MERGE (:Object {name: "' + in_objDetected + '"})'
stmt3 = 'MATCH (i1:Image{name: "' +  \
in_imgFile +  \
'"}) MATCH (o1:Object{name: "'+  \
in_objDetected +  \
'"}) CREATE (i1)-[:HAS{score: ' +  \
str(in_detScore1) +  \
'}]->(o1)'

stmt4 = 'MATCH (i1:Image{name: "' +  \
in_imgFile +  \
'"}) MATCH (o1:Object{name: "'+  \
in_objDetected +  \
'"}) CREATE (i1)-[:HAS{score: ' +  \
str(in_detScore2) +  \
'}]->(o1)'

In [9]:
print(f"stmt1={stmt1}\nstmt2={stmt2}\nstmt3={stmt3}\nstmt4={stmt4}")

stmt1=MERGE (:Image {name: "img1.jpg"})
stmt2=MERGE (:Object {name: "person"})
stmt3=MATCH (i1:Image{name: "img1.jpg"}) MATCH (o1:Object{name: "person"}) CREATE (i1)-[:HAS{score: 98.0}]->(o1)
stmt4=MATCH (i1:Image{name: "img1.jpg"}) MATCH (o1:Object{name: "person"}) CREATE (i1)-[:HAS{score: 50.0}]->(o1)


In [10]:
tx.run(stmt1, parameters=None)
tx.run(stmt2, parameters=None)
tx.run(stmt3, parameters=None)
tx.run(stmt4, parameters=None)

In [11]:
tx.commit()

In [12]:
tx.finished()

True

In [23]:
#stmt1_merge_img_node = "MERGE (:Image {name: {in_imgFile}})"
#stmt2_merge_obj_node = "MERGE (:Object {name: {in_objDetected}})"
#stmt3_rel_img_has_obj = "MATCH (i:Image{name: {in_imgFile}}) " +
#                       "MATCH (o:Object{name: {in_objDetected}}) " +
#                       "CREATE (i)-[:HAS{score: {in_detScore}}]->(o)"
#stmt3_rel_img_has_obj = "MATCH (i:Image{name: {in_imgFile}}, o:Object{name: {in_objDetected}}) CREATE (i)-[:HAS{score: {in_detScore}}]->(o)"

In [35]:
#tx.create(stmt3_rel_img_has_obj, {"in_imgFile": "img1.jpg", "in_objDetected": "person", "in_detScore": 98.45})

In [3]:
from py2neo.data import Node, Relationship
from py2neo import Graph

In [4]:
graph = Graph(uri="bolt://localhost:7687",auth=("neo4j","abc"))

In [8]:
type(graph)

py2neo.database.Graph

In [9]:
graph

<Graph database=<Database uri='bolt://localhost:7687' secure=False user_agent='py2neo/4.3.0 neobolt/1.7.17 Python/3.7.7-final-0 (linux)'> name='data'>

In [11]:
n_img = Node("Image", name="img1.jpg", size=1234)
n_obj1 = Node("Object", name="person")
n_obj2 = Node("Object", name="table")
rel_has_1 = Relationship(n_img, "HAS", n_obj1)

In [12]:
graph.create(rel_has_1)

In [7]:
help(graph.create)

Help on method create in module py2neo.database:

create(subgraph) method of py2neo.database.Graph instance
    Run a :meth:`.Transaction.create` operation within a
    :class:`.Transaction`.
    
    :param subgraph: a :class:`.Node`, :class:`.Relationship` or other
                   :class:`.Subgraph`



In [11]:
help(graph)

Help on Graph in module py2neo.database object:

data = class Graph(builtins.object)
 |  data(uri=None, **settings)
 |  
 |  The `Graph` class represents the graph data storage space within
 |  a Neo4j graph database. Connection details are provided using URIs
 |  and/or individual settings.
 |  
 |  Supported URI schemes are:
 |  
 |  - ``http``
 |  - ``https``
 |  - ``bolt``
 |  
 |  The full set of supported `settings` are:
 |  
 |  ===================  ========================================================  ==============  =========================
 |  Keyword              Description                                               Type            Default
 |  ===================  ========================================================  ==============  =========================
 |  ``auth``             A 2-tuple of (user, password)                             tuple           ``('neo4j', 'password')``
 |  ``host``             Database server host name                                

In [8]:
import sys

In [11]:
t1 = ("a", 123, 45.56)
v1, v2, v3 = t1

In [12]:
print(f"v1 = {v1} = {sys.getsizeof(v1)} bytes")
print(f"v2 = {v2} = {sys.getsizeof(v2)} bytes")
print(f"v3 = {v3} = {sys.getsizeof(v3)} bytes")
print(f"t1 = {t1} = {sys.getsizeof(t1)} bytes")

v1 = a = 50 bytes
v2 = 123 = 28 bytes
v3 = 45.56 = 24 bytes
t1 = ('a', 123, 45.56) = 80 bytes
